### ISSUE TITLE
Server Crash On Both Versions

### ISSUE THREAD

**Issue by Rohzek** [Z-Doctor/SkillTree#14]
Had a server crash happen on both 1.0.0.0: [(Crashlog)](https://pastebin.com/ruycmCAj) and on 1.0.0.1 [(Crashlog)](https://pastebin.com/19hBj4gG).

[The server itself gives a slightly better clue in the text of the report in the console window, mentioned a problem being an issue with zdoctor.mcskilltree.ModMain.proxy pointing to something that's null](https://pastebin.com/KthBFTzZ) which will probably help more than the generated crash log.

**Comment by XZcutable** [comment]
are you using the already built version, or is this a custom build?

**Comment by Rohzek** [comment]
> are you using the already built version, or is this a custom build?

Your built version; Downloaded from the Twitch launcher

**Comment by XZcutable** [comment]
sorry for the late response. downloading twitch launcher to test it.

**Comment by XZcutable** [comment]
I just downloaded and installed the launcher and the mods. I was able to open up a local world and open it to LAN. Everything worked fine on my end. But I could be not doing something you were. Do you mind providing a list of instruction to repeat the crash? Otherwise, I have no way to verify that any changes I make fix the issue.

**Comment by XZcutable** [comment]
It is also possible that your core mods are trying to interact in an unintended way with my mod.

**Comment by XZcutable** [comment]
if you also created a separate profile with just my mods and repeat whatever steps you took and don't get a crash then it will confirm to me that there was a conflict between mods somehow. Otherwise, my only guess is that it has something to do with not being able to find a constructor with some unknown parameter. I could try adding a catch-all parameter and would want to make sure you're able to test it if I do.

**Comment by XZcutable** [comment]
since it is most likely the mods you're using if you could send me a zip with the mods you have installed, that would make things 10 billion% easier.
